repos:
  - repo: local
    hooks:
      - id: ktlint-format
        name: ktlint format
        entry: ./ktlint.sh format
        language: script
        files: \.kt$
      - id: ktlint-check
        name: ktlint check
        entry: ./ktlint.sh check
        language: script
        files: \.kt$
